name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Get Cover
            uses: orgoro/coverage@v3.2
            with:
                coverageFile: ./.github/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}