name: Coverage
on:
    push:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Cover
            uses: orgoro/coverage@v3.2
            with:
                coverageFile: path/to/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}
          - name: Update README
            run: |
              sed -i "s/Coverage-[0-9]*%/Coverage-$(echo ${{ github.event.pull_request.labels }} | grep -oP '(?<=coverage=).*?(?=%)')/%" README.md